name: Comment
description: Comment on a PR (intended to be via hyperjump)
inputs:
  github-token:
    description: GitHub token
    required: true
  number:
    description: Issue/PR number
  comment:
    description: The comment text
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
