name: Fake CI for testing hyperjump

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  comment-on-prs:
    runs-on: ubuntu-latest
    name: Comment on new/updated PRs
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: post comment
        uses: ./.github/actions/post-comment
        with:
          comment: "this is a comment"
        env:
          HYPERJUMP_URL: http://github.aws.hlw3truzy4ls.com:6080/hyperjump/jump
